# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/python:3.8
  terraform-executor:
    docker:
      - image: hashicorp/terraform:0.14.3

# Define a job to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment.  
    # Add steps to the job
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
  deploy-s3:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            cd infrastructure/
            terraform init 
            terraform validate
      - run:
          name: Terraform Plan
          command: |
            cd infrastructure/
            terraform plan
      - run:
          name: Terraform Apply
          command: |
            cd infrastructure/
            terraform apply --auto-approve

# Orchestrate jobs using workflows
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy-s3:
          requires:
            - build
