# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment.
    docker:
      # 使用Python Docker镜像
      - image: python:3.8
      
    # Add steps to the job
    steps:
      # 检出代码
      - checkout

      # 安装依赖
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # 运行测试
      - run:
          name: Run tests
          command: |
            python model/test.py

# Orchestrate jobs using workflows
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
